### ISSUE TITLE
Retry: check Resilience4j implementation and interoperability with Kotlin

### ISSUE THREAD

**Issue by franciscoengenheiro** [kresil/kresil#6]
### Todo 
From kresil/ps#12:
- [x] Understand better the Retry state machine.
- [x] Understand better the context and the synchronous and asynchronous interfaces.
- [x] Understand better where the state is stored: per Retry instance, per decoration, ...
- [x] What is the registry purpose.
- [x] How to implement the retry delay
- [x] Define what is JVM platform specific

### References
  - https://github.com/resilience4j/resilience4j/issues/969
  - https://github.com/resilience4j/resilience4j/issues/77
  - https://stackoverflow.com/questions/64052854/resilience4j-new-instance-of-retry-or-retrieve-from-retryregistry

### Source code
[resilience4j](https://github.com/resilience4j/resilience4j)
- [core](https://github.com/resilience4j/resilience4j/tree/master/resilience4j-core/src/main/java/io/github/resilience4j/core)
- [retry](https://github.com/resilience4j/resilience4j/tree/master/resilience4j-retry)
- kotlin-interop:
  - [main](https://github.com/resilience4j/resilience4j/tree/master/resilience4j-kotlin/src/main/kotlin/io/github/resilience4j/kotlin/retry)
  - [test](https://github.com/resilience4j/resilience4j/tree/master/resilience4j-kotlin/src/test/kotlin/io/github/resilience4j/kotlin/retry)
